name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        tag_with_sha: true
        repository: crowdcontrol/hottub
        push: true
  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - name: 'Deploy to Kubernetes'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'hottub'
        token: '${{ github.token }}'
        namespace: 'crowdcontrol-hottub'
        chart: 'helm'
        helm: 'helm3'
        version: sha-${{GITHUB_SHA:7}}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'